Master
VityasZV/tinyraytracer pull request #15
Opened 2020-03-19 17:20 UTC by Volodimirich

Добавлена задний фон, поддержка сцен и изменён вывод

2020-03-19 17:43 UTC, VityasZV commented on CMakeLists.txt
> +#enable_cxx_compiler_flag_if_supported("-Wall")
зачем убрал?

2020-03-19 17:48 UTC, VityasZV commented on raytracing/raytracing.cpp
> +namespace BackGround
логично было бы засунуть всё это в поля структуры, а не просто накидать фактически глобальные переменные в namespace

2020-03-19 17:51 UTC, VityasZV commented on raytracing/raytracing.cpp
> +        switch (picture::Picture::scene_id) {
по завету нормальных пацанов длина функции не должна превышать 20-30 строчек, то чего можно было бы в анонимном нэймспэйсе определить функцию, которая определяет нужную шахматную доску в зависимости от сцены. в неё этот свитч и засунь

2020-03-19 17:56 UTC, VityasZV commented on raytracing/raytracing.cpp
> +//    const auto amount_of_threads = 1; //because of asynchronius tasks we can make it a bit bigger
эту строчку удоли

2020-03-19 17:58 UTC, VityasZV commented on raytracing/raytracing.cpp
> +    BackGround::width=env_width;
соответственно здесь можно в одну строчку инициализировать структуру Background

2020-03-19 18:03 UTC, VityasZV commented on raytracing/raytracing.cpp
> +    stbi_write_jpg("FINAL.jpg", width, height, 3, Npixmap.data(), 100);
теперь такой вывод на всё распространяется? и замени Final.jpg на oufile_path

2020-03-19 18:03 UTC, VityasZV requested changes
вроде отписал

2020-03-19 18:07 UTC, Volodimirich commented on CMakeLists.txt
> +#enable_cxx_compiler_flag_if_supported("-Wall")
Заебало видеть логи(

2020-03-20 12:16 UTC, Volodimirich commented on raytracing/raytracing.cpp
> +//    const auto amount_of_threads = 1; //because of asynchronius tasks we can make it a bit bigger
Done

2020-03-21 10:30 UTC, closed without merging