-out flag
VityasZV/tinyraytracer pull request #7
Opened 2020-03-11 17:57 UTC by 0smium

Реализация флага -out
Пример командной строки: ./raytracer -out finish.ppm
НО: не знаю, в какой из заголовочных файлов вынести cmdLineParams, outFilePath (и, возможно, что-то ещё?)

2020-03-11 18:19 UTC, VityasZV commented on raytracer.cpp
> +  std::unordered_map<std::string, std::string> cmdLineParams;
насчёт имён сохрани плз такой подход: 
класс/структура/enum/метод класса/функция «ИмяШтуки» 
переменная «имя_переменной» 
Так будет проще ориентироваться по коду

2020-03-11 18:20 UTC, VityasZV commented on raytracer.cpp
> +  std::unordered_map<std::string, std::string> cmdLineParams;
я всё что новое писал делал так, старые функции не менял, дабы не путаться пока смотрел статью, надо будет подкорректировать.

2020-03-11 18:21 UTC, VityasZV commented on raytracing/raytracing.cpp
> +    ofs.open(outFilePath, std::ios::binary);
out_file_path

2020-03-11 18:21 UTC, 0smium commented on raytracer.cpp
> +  std::unordered_map<std::string, std::string> cmdLineParams;
то есть пока изменить только названия?

2020-03-11 18:28 UTC, VityasZV commented on raytracer.cpp
> +    outFilePath = cmdLineParams["-out"];
всё что выше - создай наверное метод класса Picture типа PreparingOutFileAndScene, и вызови его внутри конструктора Picture (то есть теперь в конструктор будут приходить параметры argc и argv

2020-03-11 18:29 UTC, VityasZV requested changes
чутка подправь

2020-03-11 18:30 UTC, VityasZV commented on raytracer.cpp
> +  std::unordered_map<std::string, std::string> cmdLineParams;
ну да, во всём новом что пишем чтобы названия такие были

2020-03-11 18:32 UTC, VityasZV commented on raytracer.cpp
> +    outFilePath = cmdLineParams["-out"];
метод приватный пусть будет, ибо извне он нигде не нужен

2020-03-11 19:18 UTC, 0smium commented on raytracer.cpp
> +    outFilePath = cmdLineParams["-out"];
а переменную out_file_path куда лучше поместить?

2020-03-11 19:56 UTC, VityasZV commented on raytracer.cpp
> +    outFilePath = cmdLineParams["-out"];
видимо пусть поле класса picture будет, таким образом main.cpp останется такой же, но в render будет первый параметр my_pic.out_file_path.

2020-03-12 04:07 UTC, VityasZV approved these changes
В целом вссё чики пуки

2020-03-12 04:10 UTC, merged